model:
  llm: "gpt-5-mini"
  embedding: "text-embedding-3-small"
  temperature: 0

process:
  chunk_size: 3000
  chunk_overlap: 500

path:
  csv_file: "data/data_list.csv"
  files_folder: "data/parsed_json"
  vector_db: "vector_db/rfp_index"